services:
  - docker

before_script:
  - rm -rf .github/ .git/ .gitignore *.md .htaccess ./*/.htaccess docker-compose.* updateLibraries.php

jobs:
  include:
    - stage: build docker image
      script: bash ./dockerpublish.sh
